name: Update README

on:
  schedule:
    - cron: '0 * * * *' # Run every hour

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README
        run: |
          sed -i "s|<i>Last refresh</i>.*:.*<b>.*</b>|<i>Last refresh</i> : <b>$(date '+%A, %B %-d, %Y, %I:%M:%S %p')</b>|" README.md
          git add README.md
          git commit -m "Update last refresh timestamp" || echo "No changes to commit"
          git push
